myloglink: "/TXT/mylog.txt"
githublink: "https://github.com/IkhlasulHanif/os222"
author: "Ikhlasul Akmal Hanif"
title: "OS222: Operating Systems 2022-2"
tarballlink: "https://os.vlsm.org/Log/IkhlasulHanif.tar.bz2.txt"
copyright: "2022"
version: "1.0"
